# Generated by Django 3.2 on 2021-04-29 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bite', '0002_auto_20210429_0610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='modifier',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='section',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
