# Generated by Django 3.2 on 2021-04-29 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bite', '0004_auto_20210429_0959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='modifiers',
            field=models.ManyToManyField(blank=True, null=True, to='bite.Modifier'),
        ),
        migrations.AlterField(
            model_name='item',
            name='section',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bite.section'),
        ),
    ]
