# Generated by Django 3.2 on 2021-04-29 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bite', '0006_auto_20210429_1019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modifier',
            name='items',
            field=models.ManyToManyField(blank=True, to='bite.Item'),
        ),
    ]
