# Generated by Django 3.2 on 2021-04-29 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bite', '0008_auto_20210429_1041'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='modifier',
            new_name='modifiers',
        ),
    ]
